# Generated by Django 5.1.7 on 2025-03-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='formato',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
